## INSTITUTO FEDERAL DO PIAUÍ
### Curso de Tecnologia em Geoprocessamento
### Disciplina: Introdução à Linguagem Python para Análise de Dados
### Prof. Dr. Reurysson Morais

___

Como citar: 
MORAIS, R. C. de S. **GEOP-Python para Análise de Dados**. Disponível em: [osf.io/8j6ng](https://osf.io/8j6ng/). DOI 10.17605/OSF.IO/8J6NG.
___
**AULA 10: Noções básicas do NumPy (Numerical Python)**

**Objetivo**: Demonstrar operações básicas com arrays utilizado NumPy.

**Recomendação inicial:** Recomendamos fortemente a leitura do capítulo 4 do livro "Python para Análise de Dados", onde logo no início são apresentadas as razões pelas quais o numpy é um dos mais importantes pacotes para computação numérica e científica em Python. 


Referências

DOWNEY, A. B. **Pense em Python**: pense como um cientista da computação. 3. ed. Trad. Márcio Martins. São Paulo: Novatec Editora, 2024. Uma versão online gratuita está disponível em: https://penseallen.github.io/PensePython2e/.  

MCKINNEY, W. **Python para Análise de Dados**: tratamento de dados com Pandas, Numpy e Ipython. 3.ed. Trad. Aldir Coelho Corrêa da Silva. São Paulo: Novatec, 2023. Uma versão online gratuita está disponível em: https://wesmckinney.com/book/

Python.org. **Documentation**. v.3.14, 2025. Disponível em: https://docs.python.org/3.14/ .

___

In [1]:
# Importando o numpy
import numpy as np

In [ ]:
# Operações com Numpy são extremamente mais rápidas. 
# Numpy executa computações complexas em arrays inteiros sem a necessidade de loops for do Python, que em geral são lentos.

In [2]:
# Criando uma sequência de 1 milhão de números inteiros

# Utilizando array numpy
my_arr = np.arange(1000000)
print(my_arr)
# Utilizando um lista Python
my_list = list(range(1000000))


[     0      1      2 ... 999997 999998 999999]


In [3]:
# Multiplicando cada elemento do array por 2 e verificando o tempo de execução

%timeit my_arr2 = my_arr * 2

2.16 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
# Multiplicando cada elemento da lista por 2 e verificando o tempo de execução

%timeit my_list2 = [x * 2 for x in my_list]

51.7 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# Array unidimensional
list1 = [1,2,3,4,5]
arr1 = np.array(list1)

print(list1)
print(arr1)
print("Dimensão:", arr1.ndim) # ndim retorna a dimensão do array: 1 dimensão
print(arr1.shape)  # shape retorna o formato do array: uma linha com 5 elementos

[1, 2, 3, 4, 5]
[1 2 3 4 5]
Dimensão: 1
(5,)


In [7]:
# Array n-dimensional

arr2 = np.array([list1]) # Atenção ao uso dos colchetes

print(arr2)
print("Dimensão:", arr2.ndim) # ndim retorna a dimensão do array: 1 dimensão
print(arr2.shape)  # shape retorna o formato do array: uma matriz com uma linha e 5 colunas

[[1 2 3 4 5]]
Dimensão: 2
(1, 5)


In [9]:
# Array com duas dimensões (matriz m linhas e n colunas)

list2 = [[1,2,3,4,5], [6,7,8,9,10]]
arr3 = np.array(list2)

print(arr3)
arr3.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [10]:
# Array com duas dimensões (matriz m linhas e n colunas)

list3 =  [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
arr4 = np.array(list3)

print(arr4)
arr4.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)

In [12]:
# Array com três dimensões (uma matriz como m linhas e n colunas))
arr3 = np.array([
    [[1,2,3,4,5], 
     [6,7,8,9,10], 
     [11,12,13,14,15]]
])
print(arr3)
arr3.shape

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


(1, 3, 5)

In [14]:
# Array com três dimensões (duas matriz como m linhas e n colunas))
arr4 = np.array([
    [[1,2,3,4,5], 
     [6,7,8,9,10], 
     [11,12,13,14,15]],
    
    [[1,2,3,4,5], 
     [6,7,8,9,10], 
     [11,12,13,14,15]],
    
    [[1,2,3,4,5], 
     [6,7,8,9,10], 
     [11,12,13,14,15]]
    
])
print(arr4)
arr4.shape

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


(3, 3, 5)

## Operações matemáticas básicas com arrays

In [15]:
# Operações matemáticas básicas com arrays
arr1 + 5

array([ 6,  7,  8,  9, 10])

In [16]:
arr1 * 10

array([10, 20, 30, 40, 50])

In [17]:
arr1 / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [18]:
arr1 + arr1

array([ 2,  4,  6,  8, 10])

In [19]:
arr1 ** 2

array([ 1,  4,  9, 16, 25])

In [20]:
arr1

array([1, 2, 3, 4, 5])

## Funções básicas para criação de arrays 

In [21]:
# Arrays constituídos de zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
# Sequência de valores
arr5 = np.arange(15)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
np.arange(10, 101)  # (start, stop)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
np.arange(10, 101, 5)  # (start, stop, step)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [30]:
# Alterando o formato de um ndarray
arr6 = arr5.reshape(5,3)

print(arr6)
print(arr6.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
2


In [31]:
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3
(3, 3, 5)


In [32]:
# Achatando um ndarray
arr7 = arr4.flatten()
print(arr7)
print(arr7.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  1  2  3  4  5  6  7  8  9
 10 11 12 13 14 15  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1


## Indexação e fatiamento de arrays

In [34]:
arr8 = np.arange(10)
print(arr8)
print(arr8[6])
print(arr8 [3:6])

[0 1 2 3 4 5 6 7 8 9]
6
[3 4 5]


In [ ]:
arr8

In [35]:
arr8[3:6] = 5
print(arr8)

[0 1 2 5 5 5 6 7 8 9]


In [36]:
# Considere a matriz 3x3 abaixo
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# Cada linha pode ser acessada diretamente
arr2d[2]

array([7, 8, 9])

In [38]:
# Acesse a elemento i=1, j=2
arr2d[1][2]

np.int64(6)

In [39]:
# Acesse a elemento i=2, j=2
arr2d[2][2]

np.int64(9)

In [40]:
# Considere a matrix 2x2x3
arr3d = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr3d[0][1]

array([4, 5, 6])

In [43]:
arr3d[0][1][1]

np.int64(5)

Embora o fatiamento de arrays `ndarray` seja um recurso poderoso, ele pode se tornar complexo em matrizes de alta dimensão. Na prática da análise de dados, esse tipo de manipulação é frequentemente realizado com o uso do Pandas, que oferece uma interface mais intuitiva. Por isso, encerramos aqui o tema de slicing e passaremos a abordar as operações mais usuais em análise de dados