## INSTITUTO FEDERAL DO PIAUÍ
### Curso de Tecnologia em Geoprocessamento
### Disciplina: Introdução à Linguagem Python para Análise de Dados
### Prof. Dr. Reurysson Morais

___

Como citar: 
MORAIS, R. C. de S. **GEOP-Python para Análise de Dados**. Disponível em: [osf.io/8j6ng](https://osf.io/8j6ng/). DOI 10.17605/OSF.IO/8J6NG.
___
**AULA 11: Noções básicas do NumPy (Numerical Python) - Parte 2**

**Objetivo**: Demonstrar operações básicas com arrays utilizado NumPy:
- transposição de matrizes
- geração de números aleatórios
- operação matemáticas e estatísticas básicas
- operação básicas com matrizes

**Recomendação inicial:** Recomendamos fortemente a leitura do capítulo 4 do livro "Python para Análise de Dados", onde logo no início são apresentadas as razões pelas quais o numpy é um dos mais importantes pacotes para computação numérica e científica em Python. 


Referências

DOWNEY, A. B. **Pense em Python**: pense como um cientista da computação. 3. ed. Trad. Márcio Martins. São Paulo: Novatec Editora, 2024. Uma versão online gratuita está disponível em: https://penseallen.github.io/PensePython2e/.  

MCKINNEY, W. **Python para Análise de Dados**: tratamento de dados com Pandas, Numpy e Ipython. 3.ed. Trad. Aldir Coelho Corrêa da Silva. São Paulo: Novatec, 2023. Uma versão online gratuita está disponível em: https://wesmckinney.com/book/

Python.org. **Documentation**. v.3.14, 2025. Disponível em: https://docs.python.org/3.14/ .

___

In [1]:
import numpy as np

## Transposição de matrizes

In [2]:
arr = np.arange(15).reshape((3,5))

print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [3]:
arr_t = arr.T

print(arr_t)
print(arr_t.shape)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)


## Geração de números aleatórios

- Operação extremamente útil em análise de dados, especialmente em processo de obtenção de dados aleatórios oriundos de distribuições de probabilidade específicas. 
- Esse tema ficará mais claro após cursarem a disciplina de Estatística Aplicada.
- Focaremos apenas nas distribuições normal e normal padrão que são as mais comumente utilizadas em análise de dadps — pelo menos em nível introdutório. 

In [4]:
# Vamos iniciar dando uma olhada na documentação do módulo random. 
# np.random?

In [5]:
# rand: retorna números aleatórios em 0 e 1 provenientes de uma distribuição uniforme. 
amostra1 = np.random.rand(10)  # Cria uma array com 10 numeros aleatórios entre 0 e 1
amostra1

array([0.38282031, 0.38528139, 0.1556849 , 0.03729577, 0.99016827,
       0.80722487, 0.16849031, 0.41018056, 0.31873085, 0.2511245 ])

In [6]:
# rand: retorna númerso aleatórios em 0 e 1. 
amostra2 = np.random.rand(3,5)  # Cria uma matriz com m linhas de n colunas preenchidas com valores aleatórios aleatórios entre 0 e 1
amostra2

array([[0.11406084, 0.55335305, 0.84957759, 0.66000525, 0.83310396],
       [0.95916364, 0.94212884, 0.28297598, 0.35238454, 0.24600417],
       [0.67521386, 0.81684441, 0.88431422, 0.87131039, 0.85180676]])

In [7]:
# Talvez deseje obter valore(s) aleatório(os) de números inteiros que ocorrem entre dois valores (low, high). 
# Para isso use o randint(low, high, n)

amostra3 = np.random.randint(10,100, 5)   # Gera 5 números aleatórios entre 10 e 100
print(amostra3)

[54 60 38 30 10]


In [8]:
# Gera valor aleatório proveniente de uma distribuição normal com média µ e desvio pardrão σ
np.random.normal()

-1.0451188283922002

In [9]:
# Gerando um array com n valores  aleatórios proveniente de uma distribuição normal com média µ (loc) e desvio pardrão σ (scale)
np.random.normal(loc=35, scale=3, size = 10)

array([34.94271032, 30.92638878, 25.45988026, 33.85807801, 37.21870518,
       36.769656  , 39.90964863, 36.79309401, 29.11585551, 32.32312452])

In [10]:
# Gerando uma matriz mn preenchida com valores aleatórios proveniente de uma distribuição normal com média µ (loc) e desvio pardrão σ (scale)
np.random.normal(loc=35, scale=3, size = (3,3))

array([[31.66822103, 35.70678015, 34.09814535],
       [36.73182797, 36.22511179, 35.25711796],
       [34.18702376, 40.0110252 , 31.51881708]])

In [11]:
# Gerando um array com n valores aleatórios provenientes de uma distribuição normal padrão 
np.random.standard_normal(10)

array([-1.08767054, -0.88158361, -1.97846353, -0.11176531, -0.4150977 ,
        0.04462038,  0.27653788, -1.06914034,  0.44231258,  0.20558721])

In [12]:
# Gerando uma matriz mn com valores aleatórios provenientes de uma distribuição normal padrão 
np.random.standard_normal(size=(4,4))

array([[ 0.01443782,  1.34533565, -1.40100679, -1.63779091],
       [-0.59459543, -0.15004426,  0.00249003, -0.02136222],
       [-0.85144128,  0.76259581,  1.88493835, -0.51992375],
       [ 0.8277627 , -0.31258937, -0.50364923, -1.57478733]])

In [13]:
# Em algumas situação é necessário controlar o processo de seleção aleatória, especialmente quando estamos interessados
# na replicabilidade do código. Para isso, definimos o estado inicial do gerador de números aleatórios.

semente = np.random.default_rng(seed=12345)
semente.standard_normal((2,3))

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

### Algumas funções universais 

In [14]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Raiz quadrada de cada elementos de uma array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
# Quadrado de cada elemento de um array
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [17]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
rng = np.random.default_rng(42)
x = rng.standard_normal(8)
y = rng.standard_normal(8)

print("x:",x)
print("y:", y)
print("-"*30)
print("Máximo:",np.maximum(x,y))  # Retorna valores máximo elemento a elemento;

print("-"*30)
print("Mínimo:",np.minimum(x,y)) # Retorna valores mínimos elemento a elemento;

x: [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259]
y: [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307   1.12724121
  0.46750934 -0.85929246]
------------------------------
Máximo: [ 0.30471708 -0.85304393  0.87939797  0.94056472  0.0660307   1.12724121
  0.46750934 -0.31624259]
------------------------------
Mínimo: [-0.01680116 -1.03998411  0.7504512   0.77779194 -1.95103519 -1.30217951
  0.1278404  -0.85929246]


In [19]:
# Função absoluto
x_abs = np.abs(x)
print(x_abs)


# Transformação logaritmica
x_log = np.log10(x_abs)
print(x_log)

[0.30471708 1.03998411 0.7504512  0.94056472 1.95103519 1.30217951
 0.1278404  0.31624259]
[-0.5161032   0.0170267  -0.12467755 -0.02661132  0.2902651   0.11467086
 -0.89333187 -0.49997964]


### Métodos matemáticos e estatísticos básicos

In [20]:
np.random.seed(42)
arr = np.random.standard_normal((5, 4))
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [21]:
# Estatísticas da matriz

print("Soma:", arr.sum())
print("Mínimo:", arr.min())
print("Média:", arr.mean())
print("Desvio padrão:", arr.std())
print("Máximo:", arr.max())

Soma: -3.4259712288365787
Mínimo: -1.913280244657798
Média: -0.17129856144182892
Desvio padrão: 0.9357199588937781
Máximo: 1.5792128155073915


In [25]:
# Soma dos elementos de cada linhas

arr_sum_linha = arr.sum(axis=0)
print(arr_sum_linha)

[-0.97778246 -1.42887413 -0.86945825 -0.1498564 ]


In [36]:
# Soma dos elementos de cada coluna 

arr.sum(axis=1).reshape(-1, 1)

array([[ 2.52916825],
       [ 1.87835721],
       [-0.85606179],
       [-3.95852333],
       [-3.01891156]])